# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krambod', '0004_auto_20160519_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Informasjon',
            new_name='Information',
        ),
    ]
